server:
  address: 'localhost'
  port: 8080

spring:
  security:
    user:
      name: admin
      password: password
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
